version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: rideapp
    ports:
      - "5432:5432"
    volumes:
      - rideapp_data:/var/lib/postgresql/data

volumes:
  rideapp_data:
